spring:
  application:
    name: ToDoApplication
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
